{% set name = "ta" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bukosabino/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5b002749169271eddd52fe254af5a186e6c1efcac17d6f55b4e138cb2efe41f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - python >=3.6

test:
  imports:
    - ta
  commands:
    - pip check
    - python -m unittest discover
  requires:
    - pip
  source_files:
    - test

about:
  home: https://github.com/bukosabino/ta
  summary: Technical Analysis Library in Python
  description: |
    It is a Technical Analysis library useful to do feature engineering from
    financial time series datasets (Open, Close, High, Low, Volume). It is built on Pandas and Numpy.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://technical-analysis-library-in-python.readthedocs.io/en/latest/
  dev_url: https://github.com/bukosabino/ta

extra:
  recipe-maintainers:
    - BastianZim
